packages:
  - 'website'
  - 'packages/*'
  - 'packages/plugins/*'
  - 'examples/apollo-server'
  - 'examples/graphql-ws'
  - 'examples/graphql-sse'
  - 'examples/graphql-socket.io'
  - 'examples/simple-http'
  - 'examples/graphql-helix'
  - 'examples/graphql-helix-auth0'
  - 'examples/lambda-aws'
  - 'examples/azure-functions'
  - 'examples/google-cloud-functions'
  - 'examples/cloudflare-workers'
  - 'examples/with-esm'
  - 'examples/typegraphql'
  - 'examples/nexus'
  - 'examples/express-graphql'
