import type { Package } from '@guild-docs/server/npm';

export const ALL_TAGS = [
  'tracing',
  'metrics',
  'core',
  'errors',
  'security',
  'utilities',
  'performance',
  'caching',
  'devtool',
  'authentication',
  'authorization',
  'schema',
  'subscription',
] as const;

export type Tags = typeof ALL_TAGS[number];

const graphqlArmorLogoUrl = '/assets/logos/graphql-armor.svg';

export const pluginsArr: Package<Tags>[] = [
  {
    identifier: 'use-sentry',
    title: 'useSentry',
    npmPackage: '@envelop/sentry',
    iconUrl: '/assets/logos/sentry.png',
    tags: ['tracing', 'metrics', 'errors'],
  },
  {
    identifier: 'use-statsd',
    title: 'useStatsD',
    npmPackage: '@envelop/statsd',
    iconUrl: '/assets/logos/datadog.png',
    tags: ['metrics', 'errors'],
  },
  {
    identifier: 'use-schema',
    title: 'useSchema',
    githubReadme: {
      repo: 'n1ru4l/envelop',
      path: 'packages/core/docs/use-schema.md',
    },
    npmPackage: '@envelop/core',
    iconUrl: '/logo.png',
    tags: ['core', 'schema'],
  },
  {
    identifier: 'use-async-schema',
    title: 'useAsyncSchema',
    githubReadme: {
      repo: 'n1ru4l/envelop',
      path: 'packages/core/docs/use-async-schema.md',
    },
    npmPackage: '@envelop/core',
    iconUrl: '/logo.png',
    tags: ['core', 'schema'],
  },
  {
    identifier: 'use-lazy-loaded-schema',
    title: 'useLazyLoadedSchema',
    githubReadme: {
      repo: 'n1ru4l/envelop',
      path: 'packages/core/docs/use-lazy-loaded-schema.md',
    },
    npmPackage: '@envelop/core',
    iconUrl: '/logo.png',
    tags: ['core', 'schema'],
  },
  {
    identifier: 'use-error-handler',
    title: 'useErrorHandler',
    githubReadme: {
      repo: 'n1ru4l/envelop',
      path: 'packages/core/docs/use-error-handler.md',
    },
    npmPackage: '@envelop/core',
    iconUrl: '/logo.png',
    tags: ['core', 'errors'],
  },
  {
    identifier: 'use-masked-errors',
    title: 'useMaskedErrors',
    githubReadme: {
      repo: 'n1ru4l/envelop',
      path: 'packages/core/docs/use-masked-errors.md',
    },
    npmPackage: '@envelop/core',
    iconUrl: '/logo.png',
    tags: ['core', 'errors', 'security'],
  },
  {
    identifier: 'use-extend-context',
    title: 'useExtendContext',
    githubReadme: {
      repo: 'n1ru4l/envelop',
      path: 'packages/core/docs/use-extend-context.md',
    },
    npmPackage: '@envelop/core',
    iconUrl: '/logo.png',
    tags: ['core', 'utilities'],
  },
  {
    identifier: 'use-immediate-introspection',
    title: 'useImmediateIntrospection',
    githubReadme: {
      repo: 'n1ru4l/envelop',
      path: 'packages/core/docs/use-immediate-introspection.md',
    },
    npmPackage: '@envelop/core',
    iconUrl: '/logo.png',
    tags: ['core', 'utilities', 'performance'],
  },
  {
    identifier: 'use-logger',
    title: 'useLogger',
    githubReadme: {
      repo: 'n1ru4l/envelop',
      path: 'packages/core/docs/use-logger.md',
    },
    npmPackage: '@envelop/core',
    iconUrl: '/logo.png',
    tags: ['core', 'utilities'],
  },
  {
    identifier: 'use-payload-formatter',
    title: 'usePayloadFormatter',
    githubReadme: {
      repo: 'n1ru4l/envelop',
      path: 'packages/core/docs/use-payload-formatter.md',
    },
    npmPackage: '@envelop/core',
    iconUrl: '/logo.png',
    tags: ['core', 'utilities'],
  },
  {
    identifier: 'use-timing',
    title: 'useTiming',
    githubReadme: {
      repo: 'n1ru4l/envelop',
      path: 'packages/core/docs/use-timing.md',
    },
    npmPackage: '@envelop/core',
    iconUrl: '/logo.png',
    tags: ['core', 'tracing', 'utilities'],
  },
  {
    identifier: 'use-graphql-jit',
    title: 'useGraphQLJit',
    npmPackage: '@envelop/graphql-jit',
    iconUrl: '/assets/logos/graphql.png',
    tags: ['performance'],
  },
  {
    identifier: 'use-parser-cache',
    title: 'useParserCache',
    npmPackage: '@envelop/parser-cache',
    iconUrl: '/logo.png',
    tags: ['performance', 'caching'],
  },
  {
    identifier: 'use-validation-cache',
    title: 'useValidationCache',
    npmPackage: '@envelop/validation-cache',
    iconUrl: '/logo.png',
    tags: ['performance', 'caching'],
  },
  {
    identifier: 'use-data-loader',
    title: 'useDataLoader',
    npmPackage: '@envelop/dataloader',
    iconUrl: '/assets/logos/graphql.png',
    tags: ['performance', 'caching'],
  },
  {
    identifier: 'use-apollo-tracing',
    title: 'useApolloTracing',
    npmPackage: '@envelop/apollo-tracing',
    iconUrl: '/assets/logos/apollo.png',
    tags: ['devtool', 'metrics'],
  },
  {
    identifier: 'use-apollo-datasources',
    title: 'useApolloDataSources',
    npmPackage: '@envelop/apollo-datasources',
    iconUrl: '/assets/logos/apollo.png',
    tags: ['devtool', 'utilities'],
  },
  {
    identifier: 'use-open-telemetry',
    title: 'useOpenTelemetry',
    npmPackage: '@envelop/opentelemetry',
    iconUrl: '/assets/logos/opentelemetry.png',
    tags: ['tracing', 'metrics', 'errors'],
  },
  {
    identifier: 'use-generic-auth',
    title: 'useGenericAuth',
    npmPackage: '@envelop/generic-auth',
    iconUrl: '/assets/logos/generic_auth.png',
    tags: ['security', 'authentication', 'authorization'],
  },
  {
    identifier: 'use-auth0',
    title: 'useAuth0',
    npmPackage: '@envelop/auth0',
    iconUrl: '/assets/logos/auth0.png',
    tags: ['security', 'authentication', 'authorization'],
  },
  {
    identifier: 'use-graphql-modules',
    title: 'useGraphQLModules',
    npmPackage: '@envelop/graphql-modules',
    iconUrl: '/assets/logos/modules.svg',
    tags: ['schema', 'utilities', 'devtool'],
  },
  {
    identifier: 'use-rate-limiter',
    title: 'useRateLimiter',
    npmPackage: '@envelop/rate-limiter',
    iconUrl: '/assets/logos/rate_limiter.png',
    tags: ['schema', 'utilities', 'security'],
  },
  {
    identifier: 'use-disable-introspection',
    title: 'useDisableIntrospection',
    npmPackage: '@envelop/disable-introspection',
    iconUrl: '/assets/logos/graphql.png',
    tags: ['utilities', 'security'],
  },
  {
    identifier: 'use-filter-allowed-operations',
    title: 'useFilterAllowedOperations',
    npmPackage: '@envelop/filter-operation-type',
    iconUrl: '/assets/logos/graphql.png',
    tags: ['utilities', 'security'],
  },
  {
    identifier: 'use-preload-assets',
    title: 'usePreloadAssets',
    npmPackage: '@envelop/preload-assets',
    iconUrl: '/assets/logos/assets.png',
    tags: ['utilities'],
  },
  {
    identifier: 'use-persisted-operations',
    title: 'usePersistedOperations',
    npmPackage: '@envelop/persisted-operations',
    iconUrl: '/assets/logos/persisted_operations.png',
    tags: ['security', 'performance'],
  },
  {
    identifier: 'use-graphql-hive',
    title: 'useHive',
    npmPackage: '@graphql-hive/client',
    iconUrl: 'https://the-guild.dev/static/shared-logos/products/hive.svg',
    tags: ['tracing', 'metrics', 'devtool'],
  },
  {
    identifier: 'use-newrelic',
    title: 'useNewRelic',
    npmPackage: '@envelop/newrelic',
    iconUrl: '/assets/logos/newrelic.png',
    tags: ['tracing', 'metrics', 'errors'],
  },
  {
    identifier: 'use-live-query',
    title: 'useLiveQuery',
    npmPackage: '@envelop/live-query',
    iconUrl: '/assets/logos/graphql.png',
    tags: ['utilities'],
  },
  {
    identifier: 'use-fragment-arguments',
    title: 'useFragmentArguments',
    npmPackage: '@envelop/fragment-arguments',
    iconUrl: '/assets/logos/graphql.png',
    tags: ['utilities'],
  },
  {
    identifier: 'use-apollo-server-errors',
    title: 'useApolloServerErrors',
    npmPackage: '@envelop/apollo-server-errors',
    iconUrl: '/assets/logos/apollo.png',
    tags: ['utilities', 'errors'],
  },
  {
    identifier: 'use-operation-field-permissions',
    title: 'useOperationFieldPermissions',
    npmPackage: '@envelop/operation-field-permissions',
    iconUrl: '/assets/logos/graphql.png',
    tags: ['security', 'authorization'],
  },
  {
    identifier: 'use-extended-validation',
    title: 'useExtendedValidation',
    npmPackage: '@envelop/extended-validation',
    iconUrl: '/assets/logos/graphql.png',
    tags: ['devtool', 'utilities'],
  },
  {
    identifier: 'use-prometheus',
    title: 'usePrometheus',
    npmPackage: '@envelop/prometheus',
    iconUrl: '/assets/logos/prometheus.png',
    tags: ['metrics', 'errors'],
  },
  {
    identifier: 'use-context-value-per-execute-subscription-event',
    title: 'useContextValuePerExecuteSubscriptionEvent',
    npmPackage: '@envelop/execute-subscription-event',
    iconUrl: '/assets/logos/graphql.png',
    tags: ['utilities', 'subscription'],
    githubReadme: {
      repo: 'n1ru4l/envelop',
      path: '/packages/plugins/execute-subscription-event/README.md',
    },
  },
  {
    identifier: 'use-resource-limitations',
    title: 'useResourceLimitations',
    npmPackage: '@envelop/resource-limitations',
    iconUrl: '/assets/logos/rate_limiter.png',
    tags: ['schema', 'utilities', 'security'],
  },
  {
    identifier: 'use-response-cache',
    title: 'useResponseCache',
    npmPackage: '@envelop/response-cache',
    iconUrl: '/logo.png',
    tags: ['caching', 'performance'],
  },
  {
    identifier: 'use-apollo-federation',
    title: 'useApolloFederation',
    npmPackage: '@envelop/apollo-federation',
    iconUrl: '/assets/logos/apollo.png',
    tags: ['schema', 'utilities'],
  },
  {
    identifier: 'graphql-armor-max-aliases',
    title: 'maxAliasesPlugin',
    npmPackage: '@escape.tech/graphql-armor-max-aliases',
    iconUrl: graphqlArmorLogoUrl,
    tags: ['performance', 'security'],
  },
  {
    identifier: 'graphql-armor-max-depth',
    title: 'maxDepthPlugin',
    npmPackage: '@escape.tech/graphql-armor-max-depth',
    iconUrl: graphqlArmorLogoUrl,
    tags: ['performance', 'security'],
  },
  {
    identifier: 'graphql-armor-max-depth',
    title: 'maxDirectivesPlugin',
    npmPackage: '@escape.tech/graphql-armor-max-directives',
    iconUrl: graphqlArmorLogoUrl,
    tags: ['performance', 'security'],
  },
  {
    identifier: 'graphql-armor-max-tokens',
    title: 'maxTokensPlugin',
    npmPackage: '@escape.tech/graphql-armor-max-tokens',
    iconUrl: graphqlArmorLogoUrl,
    tags: ['performance', 'security'],
  },
  {
    identifier: 'graphql-armor-block-field-suggestions',
    title: 'blockFieldSuggestions',
    npmPackage: '@escape.tech/graphql-armor-block-field-suggestions',
    iconUrl: graphqlArmorLogoUrl,
    tags: ['security'],
  },
];
